// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SfSv2ACJuiDbjlxz5cLpk5asKoNlRSs',
    appId: '1:314785357094:web:95bc73534f392f42a1f5e7',
    messagingSenderId: '314785357094',
    projectId: 'zoom-c8fa9',
    authDomain: 'zoom-c8fa9.firebaseapp.com',
    storageBucket: 'zoom-c8fa9.appspot.com',
    measurementId: 'G-EZ16G908CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1fB2o6XrX7Vt8K7aOTv2vb1Ar4PaNhw',
    appId: '1:314785357094:android:3419f2d704fba800a1f5e7',
    messagingSenderId: '314785357094',
    projectId: 'zoom-c8fa9',
    storageBucket: 'zoom-c8fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWM_Jl_QHdI61Kh4rdwe3eyqpd7h-vwM',
    appId: '1:314785357094:ios:1e46a4270a665640a1f5e7',
    messagingSenderId: '314785357094',
    projectId: 'zoom-c8fa9',
    storageBucket: 'zoom-c8fa9.appspot.com',
    androidClientId: '314785357094-0u894ee18tpkvikl41hmq2l1un20avfn.apps.googleusercontent.com',
    iosClientId: '314785357094-mjrfiiar76h3nvsderkgnaajs8hnhrcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWM_Jl_QHdI61Kh4rdwe3eyqpd7h-vwM',
    appId: '1:314785357094:ios:788e1fb013ef777aa1f5e7',
    messagingSenderId: '314785357094',
    projectId: 'zoom-c8fa9',
    storageBucket: 'zoom-c8fa9.appspot.com',
    androidClientId: '314785357094-0u894ee18tpkvikl41hmq2l1un20avfn.apps.googleusercontent.com',
    iosClientId: '314785357094-3m36qp76e1m3heu5bobl6vfe25c2p9uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.management.RunnerTests',
  );
}
